### ISSUE TITLE
[FEATURE] Custom Disciplines and Skills

### ISSUE THREAD

**Issue by rdsbrazil** [Layman2501/vtm5e-clone#1]
Hello, is there a way to add custom disciplines? 
There is a lot of them missing on this version, like the Thaumaturgy Paths, also it should be included custom skills, for the secondary skills options!

Tks for the excellent job! 

PS: Have you considered creating character sheets for the other books? Like Werewolf and Mage!

**Comment by Layman2501** [comment]
I'll look into the ability to add custom skills and disciplines. 

As for other sheets we will see. I don't play many other lines so not sure what's necessary.

**Comment by Layman2501** [comment]
Reviewed the request.
Other disciplines will be added but Paths will not be added as secondary skills or put in.  Thaumaturgy rolls are just will power rolls  no secondary path roll is required to activate. The Paths can also be manually put in under Thaumaturgy already by click the +. Msg me on discord if you have trouble with it.

**Comment by TheAziraphale** [comment]
You can now add your own disciplines. New custom skills can currently not be added though, it's not very likely I will do this soon, but you can now swap between Modern, Dark Ages and Wild West skills on all sheets for the skill setup for those.
