### ISSUE TITLE
Creating a new world in Foundry 9 build 269[BUG]

### ISSUE THREAD

**Issue by Fenlander216** [Layman2501/vtm5e-clone#10]
**Describe the bug**
When making a new character sheet I can not add any dots to the skills or stats. 

**To Reproduce**
Steps to reproduce the behavior: Make a new character.

**Expected behavior**
A clear and concise description of what you expected to happen. To be able to increase or decrease the dot count on character sheets. 

Foundry 9 Build 269

**Comment by PaleLeechZak** [comment]
Did you unlock the sheet while attempting to edit the dot count for skills or stats?

**Comment by Fenlander216** [comment]
Ah I never saw that under the profile picture. Thank you.
