### ISSUE TITLE
[BUG] Unable to edit character sheet in FoundryVTT build 10.284.

### ISSUE THREAD

**Issue by weaver-of-worlds** [Layman2501/vtm5e-clone#19]
**Describe the bug**
Any editing done on the character sheets with Radio Buttons or other functionalities like them is not saved upon exiting editor mode.

**To Reproduce**
Try to edit any character sheet, things like Attributes, Abilities, Backgrounds, Humanity, Willpower etc.

**Expected behavior**
The values should have been saved, but they do not. 

**Screenshots**
![grafik](https://user-images.githubusercontent.com/103815107/188313620-46de44f3-3b67-4b3f-adfa-282034d05f75.png)

![grafik](https://user-images.githubusercontent.com/103815107/188313625-29f7a410-0f71-41ab-8790-fe665d8f62c5.png)

**Desktop (please complete the following information):**

- BrowserFirefox
- FoundryVTT Version 10

**Comment by TheAziraphale** [comment]
Hi, thanks for the bug report. The sheet currently doesn't support Version 10 of FoundryVTT. I recommend downgrading to 9 for now.

**Comment by Kerdian** [comment]
Hello, 
Foundry is now in Release 10.284, and since then, it is not possible to edit character sheets (if you add or remove a point, it doesn't take it into account).
And we cannot downgrade, because the worlds will not be compatible with version 9 once they are converted to version 10

**Comment by TheAziraphale** [comment]
I understand, I will see if I can take a look at it this week and hopefully the fix to just get it at least working on both version 9 and 10 isn't that large. 

Always good to backup worlds before upgrading to new main versions just in case plugins don't work with it. Hopefully that was done so your games are not halted.

**Comment by Kerdian** [comment]
Thank you !
I know, I should have made a backup, but in my defense, I made the update after a long game, without thinking too much... The fatigue :)

**Comment by TheAziraphale** [comment]
I have had some delays with IRL things getting in the way. I haven't forgotten about this, but it will not be done until earliest next week.

**Comment by jjpie1996** [comment]
> I have had some delays with IRL things getting in the way. I haven't forgotten about this, but it will not be done until earliest next week.

Hiya, just wondering if there has been any update to making it work with Foundry V10? i cannot edit the health, willpower or Blood points

Thank you

**Comment by Skuggkonungen** [comment]
Having the exact same problem and its grinded my vtm game to a halt. Please fix this.

**Comment by TheAziraphale** [comment]
I have been totally swamped by work so haven't had time to look at this. I will try to find time the coming week.

**Comment by TheAziraphale** [comment]
This now supports version 10, please backup your world before migrating.
