### ISSUE TITLE
[BUG] Health and Blood Pool Bars do not update Properly.

### ISSUE THREAD

**Issue by PenguinMancer** [Layman2501/vtm5e-clone#2]
**Describe the bug**
When attempting to mark health boxes or fill blood pool boxes, they do not function as intended. 
For the blood pool they appear to do nothing, or fill very briefly. For health, Superficial/Bashing damage can be marked, but when trying to click the box again to change it to another damage type results in the box simply clearing itself, and it appears the box then cannot be filled.

**To Reproduce**
Make a new world on the latest build downloaded from foundry's own browser. Make a character, then attempt to click the blood pool or health boxes. 

I am currently running on Foundry Release 0.8.9. I also tested the V5 sheet this originates from, and it appears that the health boxes there work as expected.

**Comment by Lucitus80** [comment]
I can confirm this bug.

**Comment by Layman2501** [comment]
This was caused by an updated to the vroll function rolled back the change and should work now in my testing. Feel free to reach out to me in discord Mal#6907 for quicker reply.
