### ISSUE TITLE
[FEATURE] Any update?

### ISSUE THREAD

**Issue by Panfeca** [Layman2501/vtm5e-clone#20]
Hi! I would like to ask if you are going to update the system to Foundry 10?

I really love use the system in Foundry, thanks for the amazing work. :)

**Comment by DanielNorthvolt** [comment]
I have been totally swamped by work so haven't had time to look at this. I will try to find time the coming week.

**Comment by TheAziraphale** [comment]
I have been totally swamped by work so haven't had time to look at this. I will try to find time the coming week.

**Comment by TheAziraphale** [comment]
This now supports version 10, please backup your world before migrating.

**Comment by Panfeca** [comment]
I really thank you Azi!
