### ISSUE TITLE
[BUG] Character Sheet Issues in Version 1.6

### ISSUE THREAD

**Issue by orpheus333** [Layman2501/vtm5e-clone#22]
Hello,

I just wanted to say thank you for the recent update for Foundry v10 and i wanted to list some of the issues or missing features i've been discovering while setting it up for my game. 

- the plus and minus buttons on the sheet don't seem to work for willpower, blood pool etc. I don;t know if the intention is to have these increase/decrease the max pools for these stats but at the moment both willpower and blood pool are stuck and unable to reflect players buying willpower above their courage or generations above 9th

- ghouls don't have a blood pool

**Comment by TheAziraphale** [comment]
Thanks for the highlight of the plus/minus bugs.

Fixed blood pool for ghouls as well
