### ISSUE TITLE
[FEATURE] Character Sheets for Elders

### ISSUE THREAD

**Issue by MrJingui** [Layman2501/vtm5e-clone#26]
Are there any plans for sheets for Elder kindreds of lower than 8th generation? Maximum of dots for traits like Attributes and Disciplines are 5 at the moment. Or am I blind to how I can set up traits higher than 5?

**Comment by TheAziraphale** [comment]
Try add a lower number than 8 in the generation field on the sheet and the amount of dots available should update automatically

**Comment by MrJingui** [comment]
I must be blind. I cannot find the field for Generation.

**Comment by TheAziraphale** [comment]
Description tab, row 2, 3rd box to the right
![image](https://user-images.githubusercontent.com/7412680/213037050-ebed16c0-442a-4b3e-9c4d-61d6c94c600c.png)

**Comment by TheAziraphale** [comment]
I guess this means I should move generation to the front page :)

**Comment by MrJingui** [comment]
![image](https://user-images.githubusercontent.com/122760460/213039040-14fbdb90-00f5-49ea-bd98-9adbff1f40a0.png)

I'm not seeing it there either.

**Comment by TheAziraphale** [comment]
Which sheet are you on?

**Comment by MrJingui** [comment]
![image](https://user-images.githubusercontent.com/122760460/213039258-e6bdc20e-614d-4deb-bb8a-5262e588527b.png)

**Comment by TheAziraphale** [comment]
Omg, a bug a sneaked it's way in the last release when creating new characters. I will look at it right away and get it fixed

**Comment by MrJingui** [comment]
I'll keep an eye out for the update and let you know if it's all good. :)

**Comment by TheAziraphale** [comment]
Ah, nevermind, its not a bug. But kinda unclear. Just fill in the clan field! I should really not hide this if the clan field is empty

**Comment by TheAziraphale** [comment]
If you fill in the middle field on the top where it says "clan", the sire and generation field appears. I will remove so they actually always are there in the next release I do.

**Comment by MrJingui** [comment]
Alright. Filling out the Clan field unlocks the other two. Thanks.
