### ISSUE TITLE
[FEATURE] Limits by Generation

### ISSUE THREAD

**Issue by Lucitus80** [Layman2501/vtm5e-clone#3]
Hi there, I'm missing a text field for the generation. Furthermore, is it possible to implement a limit for the fillable circles shown, so that there are only 5 dots as long as the vampire is not lower than 8th generation?

**Comment by RinVindor** [comment]
I would actually contend with maybe a toggle option to remove the Generation limitations, hard locking parts of a sheet to another part can limit the types of creatures the ST can make easily so a toggle option to remove that would be great.

**Comment by Layman2501** [comment]
@Lucitus80 https://gyazo.com/c29d7f34f3dbdc5eaebb8f871e7ff9e8 if you your generation is lower than 8 it goes down to 5 on its own. 
https://gyazo.com/e2a2456566c761c126335afce0abeacc
https://gyazo.com/be727cec134f315456fb1c5ad9c7e7d2

@RinVindor Not sure what you mean.
