### ISSUE TITLE
Difficulties with diciplines and custom rolls

### ISSUE THREAD

**Issue by ProffCreep** [Layman2501/vtm5e-clone#5]
**Describe the bug**
Difficulties cannot be set either when rolling the dice for the disciplines or in the custom rolls.
**To Reproduce**

1.1. go to the "Attributes" section in any discipline 
1.2. check rollable
1.3. roll it
1.4. without any selectable difficulty, an incorrect number of successes will be given.
1.1. create a custom roll 
1.2. check rollable
1.3. roll it
1.4. without any selectable difficulty, an incorrect number of successes will be given.

**Expected behavior**
a correct number of successes

**Desktop (please complete the following information):**

- Browser [Opera
- FoundryVTT Version [0.9]
- Foundry-V20 Version [1.4]

**Comment by TheAziraphale** [comment]
Difficulties can now be set on custom rolls, default is 6.
